In [1]:
#công thức tính mean
# μ=1/N*tongsigam(xi) i chạy từ 1 đến N (N là số data trong tập x)

In [12]:
# lập trình minh họa
def mean(x):
    t=sum(x)
    m=t/len(x)
    return m

In [13]:
x=[2,8,5,4,1,8]
m=mean(x)
m

4.666666666666667

In [1]:
# làm mờ ảnh với maen
# đọc ảnh
import cv2 as cv
import numpy as np

In [23]:
img= cv.imread('mrbean.jpg',0)# tham số ) để chuyển về ảnh xám

# tạo kernel(5*5) trượt trên ảnh
kernel=np.ones((3,3), np.float32)/9

# làm mờ ảnh
out_img=cv.filter2D(img, cv.CV_8U,kernel)

# show ảnh
cv.imshow('img', img)
cv.imshow('dst', out_img)

cv.waitKey(0)
cv.destroyAllWindows()

# lưu ý tạo kernel càng lớn thì đồ mờ của ảnh càng lớ

In [36]:
import cv2 
# làm mờ khuôn mặt của mr.bean

# dùng thư viện opencv để lấy ra ma trận vị trí khuôn mặt trong hình
face_cascade=cv2.CascadeClassifier('Haar Cascade/haarcascade_frontalface_default.xml')

# thư viện này chỉ tìm được khuôn mặ trên ảnh xám
gray_img=cv2.imread('mrbean.jpg',0)

print(gray_img)
# lấy vị trí khuôn mặt
matrix_faces= face_cascade.detectMultiScale(gray_img, 1.1,5)

#tạo kenrel
kernel= np.ones((7,7),np.float32)/49

# vẽ hình chữ nhật bao quang khuôn mặt
for (x,y,w,h) in matrix_faces:
    cv.rectangle(gray_img,(x,y),(x+w),(y+h),(0,255,0),1)
    
    roi=gray_img[y:y+h, x:x+w]
    out_roi= cv2.filter2D(roi,cv.CV_8U,kernel)
    
    gray_img[y:y+h,x:x+w]=out_roi
    
# show ảnh

cv2.imshow('img', gray_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[168 169 171 ... 101  96  98]
 [170 171 173 ...  97  90  94]
 [173 174 175 ...  94  83  90]
 ...
 [ 59  65  62 ... 248 248 248]
 [ 47  46  44 ... 248 248 248]
 [ 20  19  17 ... 248 248 248]]


error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\objdetect\src\cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
