In [4]:
# varian là độ lệnh chuẩn 
# nó là độ lệnh so với vị trí trung bình 
# minh hoạt tính varian
def mean(x):
    t=sum(x)
    return t/len(x)

def varian(x):
    me= mean(x)
    
    diff=[]
    for i in x:
        diff.append((i-me)**2)
    var = sum(diff)/len(diff)
    return var
    

In [6]:
x=[1,3,4,2,6,7]
var= varian(x)
var

4.472222222222222

In [16]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [28]:
# ứng dụng của varian để phát hiện cạnh của vật thể trong ảnh
import numpy as np
import cv2
import math
from scipy.ndimage.filters import generic_filter

img=cv2.imread('nha_tho.jpg',1) # đưa về ảnh xám
print(img)

gray_img= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

x= gray_img.astype('float')
x_filt= generic_filter(x,np.std, size=2) # sử dụng hàm generic_filter truyền vào ảnh , np.std là hàm tính độ lệnh chuẩn, size là độ lớn của kernel

# lọc loại bỏ những giá trị nhỏ hơn 20
x_filt[x_filt <20]=0

# tăng độ sáng cảu điểm ảnh của x_filt để cho rõ ràng
x_filt=x_filt *2.5

cv2.imshow('input',img)
cv2.imshow('out', x_filt)

cv2.waitKey(0)
cv2.destroyAllWindows()



[[[123  49  31]
  [123  49  31]
  [123  49  31]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[123  49  31]
  [123  49  31]
  [124  50  32]
  ...
  [  4   4   4]
  [  4   4   4]
  [  4   4   4]]

 [[123  49  31]
  [123  49  31]
  [124  50  32]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 19 128 179]
  [ 17 129 181]
  [ 16 132 185]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 17 116 166]
  [ 16 117 169]
  [ 16 120 173]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 16 108 157]
  [ 16 108 159]
  [ 15 111 164]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
