In [3]:
#import thư viện numpy
import numpy as np

In [11]:
#tạo vector với numpy hay còn gọi là mảng 1 chiều
list1= [1,2,3,4]
data= np.array(list1)
print(data)
# cách khác để tạo mảng 1 chiều
data1= np.array([1,2,3,4])
print(data1)
print(data.shape)
# shape của vector data=4 tức là 1 vector có 1 hàng 4 cột

[1 2 3 4]
[1 2 3 4]
(4,)


In [15]:
# taọ mảng 2 chiều hay còn gọi là ma trận 
# cách 1
list2= [[1,2,3],[4,5,6]]
matrix= np.array(list2)
print(matrix)
#cách 2
matrix2=np.array([[2,0,1],
                   [4,1,2]])
print(matrix2)
print('shape của matrix là:', matrix.shape)

[[1 2 3]
 [4 5 6]]
[[2 0 1]
 [4 1 2]]
shape của matrix là: (2, 3)


In [18]:
# tạo 1 mảng 3 chiều
# cũng có 2 cách như trên
list3=[[[1,2],[3,4],[4,5]],
       [[-1,3],[0,0],[1,2]],
       [[5,6],[7,8],[9,10]]]
data3=np.array(list3)
print(data3)
print('shape của mảng trên là:' , data3.shape)

[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[-1  3]
  [ 0  0]
  [ 1  2]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]
shape của mảng trên là: (3, 3, 2)


In [24]:
# kiểu dữ liệu
#tạo vector data1
data1=np.array([1,2,3,4])
print('kiểu dữ liệu của data1 là:', data1.dtype)

# tạo vector data2 có kiểu float
data2=np.array([8.6, 0.7, 4.5])
print('kiểu dữ liệu của data2 là:', data2.dtype)

# khi tạo ta chọn kiểu 
data3=np.array([8,9,0,7], dtype=np.int64)
print('kiểu dữ liệu của data3 là:', data3.dtype)

kiểu dữ liệu của data1 là: int32
kiểu dữ liệu của data2 là: float64
kiểu dữ liệu của data3 là: int64


In [37]:
# các hàm tạo ma trận khác
# hàm taọ ma trận toàn số 0
matrix_zeros=np.zeros((3,4))
print(matrix_zeros)

# hàm tạo ma trận toàn số 1 
matrix_ones= np.ones((2,1))
print(matrix_ones)

# hàm tạo ma trận đơn vị
matrix_eyes=np.eye((3))
print(matrix_eyes)

# hàm tạo vector tuần tự np.arange(start,stop,step)
arr= np.arange(1,5)
arr1=np.arange(0,5,2)
print(arr)
print(arr1)

# hàm random, tạo matrix ngẫu nhiên 2 hàng 2 cột
arr_random= np.random.random((2,2))
print(arr_random)
# giá trị random nằm trong khoảng 0 đến 1

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.]
 [1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3 4]
[0 2 4]
[[0.77738393 0.64878491]
 [0.81193108 0.4456218 ]]


In [44]:
#tạo mảng theo điều kiện nào đó
arr2= np.arange(5)
boolean_vector=arr2>2
print(arr2)
print(boolean_vector)
condition= np.where(boolean_vector,arr2,arr2*5)
print(condition)

[0 1 2 3 4]
[False False False  True  True]
[ 0  5 10  3  4]


In [49]:
# duỗi matrix nhiều chiều về 1 chiều
arr3= np.array([[1,2],[4,5],[6,7]])
out= arr3.flatten()
print(arr3)
print(out)

[[1 2]
 [4 5]
 [6 7]]
[1 2 4 5 6 7]


In [54]:
# reshape matrix
arr4=np.array([[1,2],[3,4],[5,6]])
print(arr4, arr4.shape)

# ta sẽ thay đổi kích cỡ của ma trận trên
out1= np.reshape(arr4,(2,3))
print('matrix sau thay đổi kích cỡ\n',out1,out1.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
matrix sau thay đổi kích cỡ
 [[1 2 3]
 [4 5 6]] (2, 3)


In [60]:
# index của mảng
# tạo mảng 2 chiều
arr5=np.array([[1,2,3,4],
               [3,4,5,6],
               [5,6,7,7]])
print(arr5)

# tìm tất cả các phần tử của cột 1
col1_arr5=arr5[:,1]
print('tất cả phần tử của cột 1:',col1_arr5)

# tìm tất cả phần tử của hàng 2 và 3
col2_3=arr5[1:,:]
print(col2_3)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 7]]
tất cả phần tử của cột 1: [2 4 6]
[[3 4 5 6]
 [5 6 7 7]]


In [64]:
# các phép toán trên array
# phép cộng 
x=np.array([[1,2,3,4],[3,2,1,6]])
y=np.array([[3,1,-2,5],[7,-1,0,1]])
#cách 1
z=x+y
print(z)
#cách 2
z1=np.add(x,y)
print('cộng cách 2:\n', z1)

# phép trừ tương tự thay hàm add bằng z=subtract(x,y)
# lưu ý các array cộng với nhau phải có cỡ bằng nhau

[[ 4  3  1  9]
 [10  1  1  7]]
cộng cách 2:
 [[ 4  3  1  9]
 [10  1  1  7]]


In [70]:
# phép nhân từng vị trí của array1 với array2
# lưu ý 2 array phải có cỡ bằng nhau
z2=x*y
print('cách1:\n', z2)
print('cách 2:\n' ,np.multiply(z,y))
# phép chia từng vị trí cũng  như thế

cách1:
 [[ 3  2 -6 20]
 [21 -2  0  6]]
cách 2:
 [[12  3 -2 45]
 [70 -1  0  7]]


In [77]:
# phép nhân ma trận
# lưu ý khi nhân phải chú ý kích cỡ ma trận
# 2 matrix a và b nhân được với nhau khi số cột matrix thứ nhất bằng số hàng matrix thứ 2
# vd: A(a,b)*B(b,c)=C(a,c)
x1=np.array([[1,2],[2,3],[3,4]])
y1=np.array([[1,2,-3,6],[-7,1,2,6]])
z3=x1.dot(y1)
print('matrix x:\n',x1)
print('matrix y:\n',y1)
print('matrix kết pảu phép nhân z=x*y\n',z3)
print('cách 2:\n', np.dot(x1,y1))
# lưu ý phép nhân ma trận không có tính giao hoán

matrix x:
 [[1 2]
 [2 3]
 [3 4]]
matrix y:
 [[ 1  2 -3  6]
 [-7  1  2  6]]
matrix kết pảu phép nhân z=x*y
 [[-13   4   1  18]
 [-19   7   0  30]
 [-25  10  -1  42]]
cách 2:
 [[-13   4   1  18]
 [-19   7   0  30]
 [-25  10  -1  42]]


In [81]:
# ma trận chuyển vị
# chuyển hàng thành cột và cột thành hàng
#vd: A(2,3) ==> A(3,2)
arr6=np.array([[5,6,7],[1,2,3]])
out4=arr6.T
print(out4)

[[5 1]
 [6 2]
 [7 3]]


In [93]:
# tính tông 1 matrix
arr7=np.array([[1,2,5,-9],[3,4,7,-10],[1,3,4,2]])
print(arr7)
# tổng tất cả các phần tử
t= np.sum(arr7)
print('tổng tất cả các phần tử:\n',t)

print('tổng từng hàng:\n', np.sum(arr7,axis=1))
print('tổng từng cột;\n', np.sum(arr7,axis=0))
# lưu ý theo tác trên cột thì axis=0 còn trên hàng axis=1
# hàm max, min tương tự thay bằng hàm np.max(), np.min()

[[  1   2   5  -9]
 [  3   4   7 -10]
 [  1   3   4   2]]
tổng tất cả các phần tử:
 13
tổng từng hàng:
 [-1  4 10]
tổng từng cột;
 [  5   9  16 -17]
