In [3]:
# median là lấy giá trị ở giữa của 1 dãy số(dãy số phải sắp xếp)
# công thức tính median với dãy số x và độ dài m
# m lẻ thì median= x[m/2+1]
# m chẵn thì median=(x[m/2]+x[m/2+1])/2

# lập trình mô tả thuật toán
def median(x):
    x.sort()
    if len(x)%2==0:
        m1= len(x)/2
        m2= len(x)/2+1
        m1= int(m1)-1
        m2= int(m2)-1
        median=(x[m1] + x[m2])/2
    else:
        m=len(x)/2
        m= int(m)-1
        median=x[m]
    return median

In [7]:
x=[1,4,2,6,8,3]
med=median(x)
med

3.5

In [12]:
# ứng dụng của median để khử nhiễu trong ảnh
# opencv cung cấp hàm medianBlur() để khử nhiễu trong ảnh bằng median
import cv2
import numpy as np

# đọc ảnh
img=cv2.imread('salt_pepper.jpg')
print(img)

#dùng hàm medianBlur để khử nhiễu

out_img=cv2.medianBlur(img,3) # kernel mà lớn thì sẽ làm mờ ảnh

cv2.imshow('int-img',img)
cv2.imshow('out-img',out_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0   0   0]
  [ 10  10  10]
  [  1   1   1]
  ...
  [254 254 254]
  [  0   0   0]
  [  4   4   4]]

 [[  6   6   6]
  [242 242 242]
  [255 255 255]
  ...
  [252 252 252]
  [254 254 254]
  [ 14  14  14]]

 [[  1   1   1]
  [254 254 254]
  [255 255 255]
  ...
  [253 253 253]
  [253 253 253]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [254 254 254]
  [255 255 255]
  ...
  [252 252 252]
  [255 255 255]
  [  3   3   3]]

 [[  0   0   0]
  [255 255 255]
  [253 253 253]
  ...
  [255 255 255]
  [253 253 253]
  [  1   1   1]]

 [[  2   2   2]
  [  0   0   0]
  [  1   1   1]
  ...
  [  2   2   2]
  [  0   0   0]
  [  6   6   6]]]
